# Generated by Django 2.2.2 on 2019-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
