# Generated by Django 2.2.2 on 2019-07-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_isteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='classroom',
            field=models.CharField(default='room1', max_length=255),
        ),
    ]
