# Generated by Django 2.2.2 on 2019-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190710_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default='01012345678', max_length=20),
            preserve_default=False,
        ),
    ]
