# Generated by Django 2.2.2 on 2019-07-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190712_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='textbook',
        ),
        migrations.CreateModel(
            name='TextbookCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Checkpoint')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Textbook')),
            ],
        ),
        migrations.AddField(
            model_name='textbook',
            name='checkpoints',
            field=models.ManyToManyField(blank=True, related_name='textbooks', through='api.TextbookCheckpoint', to='api.Checkpoint'),
        ),
    ]
