# Generated by Django 2.2.2 on 2019-07-15 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_textbook_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbook',
            name='file',
            field=models.FileField(default='ok', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
