# Generated by Django 2.1.7 on 2019-06-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer_connection',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('peer_id', models.TextField(max_length=20)),
                ('peer_connection', models.TextField()),
                ('chat_room', models.CharField(max_length=50)),
            ],
        ),
    ]
