export const UPDATE_ONLINE_USERS = 'UPDATE_ONLINE_USERS';
export const UPDATE_MY_PEER = 'UPDATE_MY_PEER';
export const UPDATE_LOCALSTREAM = 'UPDATE_LOCALSTREAM';
export const UPDATE_SOCKET = 'UPDATE_SOCKET';
export const RESET_PEER_MANAGER = 'RESET_PEER_MANAGER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';