export const UPDATE_PEER = 'UPDATE_PEER';
export const DELETE_PEER = 'DELETE_PEER';
export const UPDATE_MY_PEER = 'UPDATE_MY_PEER';
export const UPDATE_LOCALSTREAM = 'UPDATE_LOCALSTREAM';
export const UPDATE_SOCKET = 'UPDATE_SOCKET';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const RETURN_ERRORS = 'RETURN_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
